image:
  repository: public.ecr.aws/aws-containers/retail-store-sample-checkout
  pullPolicy: IfNotPresent
  tag: 1.3.0

redis:
  create: false

app:
  persistence:
    provider: redis
    redis:
      endpoint: "retail-dev-checkout-redis.cddrmd.0001.use1.cache.amazonaws.com:6379"   # from terraform output
  endpoints:
    orders: http://orders

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi